service: auth-server

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  timeout: 60
  environment: 
  # Syntax: 1) look in the same folder for a file called config.json, 2) get the value of CLIENT_ID, and 3) assign it as an environment variable to CLIENT_ID
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    PROJECT_ID: ${file(config.json):PROJECT_ID}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
  getAccessToken:
    handler: handler.getAccessToken
    events: 
      - http:
          path: api/token/{code} # code will be an URI parameter for example user?name=john&age=25
          method: get
  getCalenderEvents:
    handler: handler.getCalenderEvents
    events:
      - http:
          path: api/get-events/{access_token}
          method: get